### ISSUE TITLE
Show multiple rewards when applicable

### ISSUE THREAD

**Issue by groninge01** [beethovenxfi/frontend-v2#18]
![image](https://user-images.githubusercontent.com/20125808/155873999-e3f9c4ab-69c8-4f1b-820d-253f5a5b2704.png)

**Comment by groninge01** [comment]
@danielmkm There is only room for one extra reward token in the backend data right now. I will try to come up with a simple design for now then.

**Comment by 0xSkly** [comment]
something which would be nice is that if the rewarder is empty, the apr for the reward token should go to 0%. think it now just checks the `rewards/second`.

**Comment by groninge01** [comment]
Fixed by @danielmkm 

![image](https://user-images.githubusercontent.com/20125808/163019458-cc21c65f-a8b2-4964-91de-870f2613c514.png)
